# Generated by Django 2.1.11 on 2019-12-12 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_cloud', '0012_documentcrawler_error_key'),
        ('document_cloud', '0012_change_document_cloud_search_query_type_to_types'),
    ]

    operations = [
    ]
